// @ts-check
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const topicMap = require('./topics/topic-map.json');

const seen = new Set();

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = Object.fromEntries(
  topicMap.mappings
    .filter(({ category }) => {
      if (seen.has(category)) return false;
      seen.add(category);
      return true;
    })
    .map(({ category }) => [
      `${category}Sidebar`,
      [{ type: 'autogenerated', dirName: category }],
    ])
);

export default sidebars;
