// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  programsSidebar: [
    { type: 'autogenerated', dirName: 'programs' },
  ],
  pluginsSidebar: [
    { type: 'autogenerated', dirName: 'plugins' },
  ],
};

export default sidebars;
