// @ts-check
import { existsSync, readdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import { createRequire } from 'module';

const __dirname = dirname(fileURLToPath(import.meta.url));
const require   = createRequire(import.meta.url);
const topicMap  = require('./topics/topic-map.json');

function categoryHasContent(category) {
  try {
    const abs = join(__dirname, 'docs', category);
    return existsSync(abs) && readdirSync(abs).length > 0;
  } catch {
    return false;
  }
}

const seen = new Set();

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = Object.fromEntries(
  topicMap.mappings
    .filter(({ category }) => {
      if (seen.has(category)) return false;
      seen.add(category);
      return true;
    })
    .map(({ category }) => {
      const dirName = categoryHasContent(category) ? category : `mock/${category}`;
      return [`${category}Sidebar`, [{ type: 'autogenerated', dirName }]];
    })
);

export default sidebars;
