// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  programsSidebar: [
    {
      type: 'category',
      label: 'InputBar',
      link: { type: 'doc', id: 'programs/inputbar/readme' },
      items: [{ type: 'autogenerated', dirName: 'programs/inputbar' }],
    },
    {
      type: 'category',
      label: 'Premiere Companion',
      link: { type: 'doc', id: 'programs/premiere-companion/readme' },
      items: [{ type: 'autogenerated', dirName: 'programs/premiere-companion' }],
    },
  ],
  pluginsSidebar: [
    {
      type: 'category',
      label: 'Plugins',
      items: [{ type: 'autogenerated', dirName: 'plugins' }],
    },
  ],
};

export default sidebars;
